// Copyright 2024 the JSR authors. All rights reserved. MIT license.

locals {
  worker_download_analytics_dataset = "${var.gcp_project}-downloads"
}

// The LB worker is deployed with `wrangler deploy` (not Terraform): the
// cloudflare provider can't set a container image or roll one out, and Durable
// Object migrations don't fit its per-deploy version model. `wrangler deploy`
// handles the image, the DO migration (idempotent by tag), and the container
// rollout in one command.
//
// To avoid duplicating every value out of tfvars into a hand-written
// wrangler.jsonc, Terraform RENDERS the worker config here from the values it
// already owns. CI runs `terraform apply` (which writes lb/wrangler.json for
// the current environment) and then `wrangler deploy`. Secrets are not in this
// file — they're generated by Terraform (the outputs below) and delivered with
// `wrangler secret bulk` (see tools/lb-secret-bulk.ts).

# NOTE: this file is intended to be rendered from CI. Running `terraform apply`
# locally overwrites lb/wrangler.json with a config pinned to whatever
# api_image_tag you pass (there is no default, so a bare apply fails loudly).
resource "local_file" "lb_wrangler_config" {
  filename = "${path.module}/../lb/wrangler.json"
  content = jsonencode({
    name               = "${var.gcp_project}-jsr-lb"
    main               = "dist/main.js"
    compatibility_date = "2026-05-19" # keep in sync with cloudflare_frontend.tf

    observability = {
      enabled            = true
      head_sampling_rate = 0.01
      logs               = { enabled = true, invocation_logs = true }
    }

    migrations = [
      { tag = "v1", new_sqlite_classes = ["ApiContainer"] }
    ]

    durable_objects = {
      bindings = [
        { name = "API_CONTAINER", class_name = "ApiContainer" }
      ]
    }

    # max_instances must match API_CONTAINER_INSTANCES in lb/main.ts (getRandom
    # spreads requests across that many stable DO IDs, each capped at one
    # container). The API server runs near a full CPU (Cloud Run sits at ~90% of
    # 1 vCPU), so 1 vCPU; Cloudflare requires >= 3 GiB per vCPU for custom
    # instance types, so memory is 3 GiB (only ~512 MiB is actually used).
    containers = [
      {
        class_name    = "ApiContainer"
        image         = "registry.cloudflare.com/${var.cloudflare_account_id}/jsr-api:${var.api_image_tag}"
        max_instances = 30
        instance_type = {
          vcpu       = 1
          memory_mib = 3072
          disk_mb    = 2048
        }
      }
    ]

    routes = [
      { pattern = "${var.domain_name}/*", zone_id = var.cloudflare_zone_id },
      { pattern = "${local.api_domain}/*", zone_id = var.cloudflare_zone_id },
      { pattern = "${local.npm_domain}/*", zone_id = var.cloudflare_zone_id },
    ]

    analytics_engine_datasets = [
      { binding = "DOWNLOADS", dataset = local.worker_download_analytics_dataset }
    ]

    r2_buckets = [
      { binding = "MODULES_BUCKET", bucket_name = cloudflare_r2_bucket.modules.name },
      { binding = "NPM_BUCKET", bucket_name = cloudflare_r2_bucket.npm.name },
    ]

    services = [
      { binding = "FRONTEND", service = "${var.gcp_project}-jsr-frontend" }
    ]

    ratelimits = [
      {
        name         = "FRONTEND_RATELIMIT"
        namespace_id = "1001"
        simple       = { limit = 120, period = 60 }
      }
    ]

    // Non-secret config the LB worker reads or forwards to the API container
    // (see lb/containers.ts). Secrets are delivered separately.
    vars = {
      ROOT_DOMAIN                  = var.domain_name
      API_DOMAIN                   = local.api_domain
      NPM_DOMAIN                   = local.npm_domain
      METADATA_STRATEGY            = "service_account_key"
      PUBLISHING_BUCKET            = cloudflare_r2_bucket.publishing.name
      MODULES_BUCKET_NAME          = cloudflare_r2_bucket.modules.name
      DOCS_BUCKET                  = cloudflare_r2_bucket.docs.name
      NPM_BUCKET_NAME              = cloudflare_r2_bucket.npm.name
      S3_REGION                    = "auto"
      S3_ENDPOINT                  = "${var.cloudflare_account_id}.r2.cloudflarestorage.com"
      GITHUB_CLIENT_ID             = var.github_client_id
      GITLAB_CLIENT_ID             = var.gitlab_client_id
      REGISTRY_URL                 = "https://${var.domain_name}"
      NPM_URL                      = "https://${local.npm_domain}"
      EMAIL_FROM                   = "help@${var.domain_name}"
      EMAIL_FROM_NAME              = var.email_from_name
      PUBLISH_QUEUE_ID             = "projects/${var.gcp_project}/locations/us-central1/queues/${local.publishing_tasks_queue_name}"
      NPM_TARBALL_BUILD_QUEUE_ID   = "projects/${var.gcp_project}/locations/us-central1/queues/${local.npm_tarball_build_tasks_queue_name}"
      CLOUDFLARE_ACCOUNT_ID        = var.cloudflare_account_id
      CLOUDFLARE_ZONE_ID           = var.cloudflare_zone_id
      CLOUDFLARE_ANALYTICS_DATASET = local.worker_download_analytics_dataset
    }
  })
}

// Secret values consumed by the LB worker. Generated/owned by Terraform and
// delivered to the wrangler-managed worker via `wrangler secret bulk` in CI.
output "lb_database_url" {
  sensitive = true
  value     = "postgres://${google_sql_user.api.name}:${google_sql_user.api.password}@${google_sql_database_instance.main_pg15.public_ip_address}/${google_sql_database.database.name}?sslmode=require"
}

output "lb_gcp_service_account_key" {
  sensitive = true
  value     = base64decode(google_service_account_key.registry_api.private_key)
}

output "lb_s3_access_key" {
  sensitive = true
  value     = cloudflare_account_token.buckets_rw.id
}

output "lb_s3_secret_key" {
  sensitive = true
  value     = local.r2_secret_access_key
}
