gcp_project                   = "deno-registry3-staging"
domain_name                   = "deno-registry-staging.net"
email_from_name               = "Deno Registry Staging"
orama_package_public_api_key  = "jZPVJccROdHgJrohf3WJIaTXGLNfIVSI"
orama_package_public_index_id = "jsr-staging-x84zqv"
orama_docs_public_api_key     = "wxhe9MwCJf4ArRUmthZjkR4fisStO2I3"
orama_docs_public_index_id    = "jsr-docs-staging-y01k25"
github_client_id              = "Iv1.b30125ad4e70d4c1"
