gcp_project           = "deno-registry3-staging"
domain_name           = "deno-registry-staging.net"
email_from_name       = "Deno Registry Staging"
orama_public_api_key  = "jZPVJccROdHgJrohf3WJIaTXGLNfIVSI"
orama_public_index_id = "jsr-staging-x84zqv"
github_client_id      = "Iv1.b30125ad4e70d4c1"
