name: Orama Reindex

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deployment"
        type: choice
        options:
          - prod
          - staging
        required: true

jobs:
  reindex_orama:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - name: Deploy
        env:
          ORAMA_INDEX_ID: ${{ secrets.ORAMA_INDEX_ID }}
          ORAMA_PRIVATE_API_KEY: ${{ secrets.ORAMA_PRIVATE_API_KEY }}
          JSR_URL: ${{ vars.ENVIRONMENT_URL }}
        run: deno task tools:orama:reindex
